apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ljvh
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0045-tenant/tkrw-pr712-0075-0045-app/devfile-sample-ljvh@sha256:916d088185695fc275d4714df0376c30091bbfb710e596c6f3bcbe4ba56ce84d
        name: my-nodejs
        resources: {}
status: {}
